### PR TITLE
chore: transplant docker updatecli manifest from kubernetes-management

### PR DESCRIPTION
**Pull request by lemeurherve**

### CODE REVIEW

**Comment by lemeurherve** [comment]
Related: https://github.com/jenkins-infra/kubernetes-management/pull/1838

**Review by dduportal — APPROVED** [review]
Approving:
- We don't have (yet) any CI check (either GH Actions, Jenkins, or both) that would take care if running these
- It's literraly transplanting settings

**Review by dduportal — COMMENTED** [review]
s/Jenkinsfile/Jenkinsfile_k8s/ no ?

**Comment by lemeurherve** [comment]
Related: https://github.com/jenkins-infra/kubernetes-management/pull/1842

**Pull request merged**
