### PR TITLE
Accepts updates on phs with review

### PR DESCRIPTION
**Pull request by alecharp**
If we can get an automatic review request from `updatecli` (https://github.com/updatecli/updatecli/issues/925), this could speed up the process.

### CODE REVIEW

**Review by dduportal — APPROVED** [review]
I've added you as writer in this repo (otherwise the GH API would ignore the request to add you as reviewer).

But nice idea!

**Comment by lemeurherve** [comment]
In the mean time I propose https://github.com/marketplace/actions/auto-assign-reviewer-by-files, WDYT?

**Comment by alecharp** [comment]
@lemeurherve absolutely. Anything that work for you all. I was just looking to limit the amount of work you have.

**Comment by lemeurherve** [comment]
I've limited the amount of work with this simple PR: https://github.com/jenkins-infra/helm-charts/pull/315

**Comment by lemeurherve** [comment]
@alecharp should we close this PR?

**Comment by alecharp** [comment]
I think we can yes.

**Pull request closed without merging**
